/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.hospital;

import ui.doctor.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import model.DoctorDirectory;
import model.PatientDirectory;
import ui.patient.PatientListJPanel;

/**
 *
 * @author Jiale Lyu
 */
public class HospitalAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    JPanel mainWorkArea;
    DoctorDirectory doctorDirectory;
    PatientDirectory patientDirectory;
    public HospitalAdminJPanel(JPanel mainWorkArea, DoctorDirectory doctorDirectory, PatientDirectory patientDirectory) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.doctorDirectory = doctorDirectory;
        this.patientDirectory = patientDirectory;
        lblWelcome.setText("Welcome to Doctor Page!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuBar = new javax.swing.JPanel();
        btnManageDoctor = new javax.swing.JButton();
        btnManagePatient = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        btnManageDoctors = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuBar.setBackground(new java.awt.Color(255, 255, 255));

        btnManageDoctor.setText("Manage Doctors");
        btnManageDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDoctorActionPerformed(evt);
            }
        });

        btnManagePatient.setText("Manage Patients");
        btnManagePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnManageDoctor)
                .addGap(64, 64, 64)
                .addComponent(btnManagePatient)
                .addGap(36, 36, 36)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageDoctor)
                    .addComponent(btnManagePatient)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(menuBar);

        workArea.setLayout(new java.awt.CardLayout());

        lblWelcome.setText("<WelcomeMsg>");

        javax.swing.GroupLayout btnManageDoctorsLayout = new javax.swing.GroupLayout(btnManageDoctors);
        btnManageDoctors.setLayout(btnManageDoctorsLayout);
        btnManageDoctorsLayout.setHorizontalGroup(
            btnManageDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManageDoctorsLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        btnManageDoctorsLayout.setVerticalGroup(
            btnManageDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManageDoctorsLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(lblWelcome)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        workArea.add(btnManageDoctors, "card2");

        jSplitPane1.setRightComponent(workArea);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDoctorActionPerformed
        DoctorListJPanel panel = new DoctorListJPanel(workArea,doctorDirectory);
        workArea.add("ViewDoctorJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnManageDoctorActionPerformed

    private void btnManagePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientActionPerformed
        PatientListJPanel panel = new PatientListJPanel(workArea, patientDirectory);
        workArea.add("ViewPatientJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnManagePatientActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
//        LoginJPanel loginPanel = (LoginJPanel) component;
//        loginPanel.populateSupplierCombo();
        
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageDoctor;
    private javax.swing.JPanel btnManageDoctors;
    private javax.swing.JButton btnManagePatient;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
